#! /usr/bin/perl

$FNAME="FundamentalError";

system("pdftotext $FNAME.pdf");

open(INFILE,"$FNAME.txt");
open(OUTFILE,">$FNAME.textonly.txt");

while(<INFILE>){
	chomp;
	s/\f//g;
	s/\xAD/-/g;
	if(/^FUNDAMENTAL CONFIDENCE FALLACY/){
		<INFILE>;
		<INFILE>;
	}else{
		print(OUTFILE "$_")
	}
}

close(INFILE);

close(OUTFILE);

unlink("$FNAME.txt");

system("cat $FNAME.textonly.txt | wc -w > wc.tex");
system("cat wc.tex");
